<?php

namespace AppBundle\Repository;

/**
 * AppointmentAvailabilityNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentAvailabilityNotificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAppointmentAvailabilityFromToken($token)
    {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.token= :token')
            ->andWhere('a.answer IS NULL')
            ->setParameter('token', $token)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findAppointmentAvailabilityFromClient($client)
    {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.eventToReplace', 'event_to_replace')
            ->where('event_to_replace.client = :client')
            ->andWhere('a.answer IS NULL')
            ->setParameter('client', $client)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findLastAppointmentNotificationSent($event)
    {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.eventFreed = :event')
            ->setParameter('event', $event)
            ->orderBy('a.createdAt', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findAppointmentNotificationSent($event)
    {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.eventFreed = :event')
            ->setParameter('event', $event)
            ->orderBy('a.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
