<?php

namespace AppBundle\Repository;

/**
 * CellCarrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CellCarrierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAvailable()
    {
        return $this->createQueryBuilder('cc')
            ->where('cc.available = 1')
            ->orderBy('cc.name', 'ASC');
    }
}
