<?php

namespace AppBundle\Repository;

/**
 * CoordinateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPrimary()
    {
        return $this->createQueryBuilder('cc')
            ->where('cc.primary = 1')
            ->orderBy('cc.name', 'ASC');
    }
}
