<?php

namespace AppBundle\Repository;

/**
 * EventReminderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventReminderRepository extends \Doctrine\ORM\EntityRepository
{
}
