<?php

namespace AppBundle\Repository;

/**
 * EventCancellationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCancellationRepository extends \Doctrine\ORM\EntityRepository
{
}
