<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Employe;

/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByEmployee(Employe $employe)
    {
        return $this->createQueryBuilder('s')
            ->select('s')
            ->where('s.employe = :employe')
            ->setParameter('employe', $employe)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
