<?php

namespace AppBundle\Repository;
use Faker\Provider\cs_CZ\DateTime;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserFromToken($token)
    {
        return $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.resetPasswordToken = :token')
            ->andWhere('u.resetPasswordDate IS NULL')
            ->setParameter('token', $token)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findUserFromEmail($email)
    {
        return $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.email = :email')
            ->setParameter('email', $email)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}