imports:
    - { resource: parameters.yml }
    - { resource: parameters.php }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

cspoo_swiftmailer_mailgun:
    key: "%mailgun_key%"
    domain: "%mailgun_domain%"
    #http_client: 'httplug.client' # Optional. Defaults to null and uses discovery to find client.

# Swiftmailer Configuration
swiftmailer:
    transport: "mailgun"
    spool:     { type: memory }
    #transport: "%mailer_transport%"
    #host:      "%mailer_host%"
    #username:  "%mailer_user%"
    #password:  "%mailer_password%"


# KNP Paginator
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

# Vich Uploader
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        receipt:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /receipts_pdf
            upload_destination: '%kernel.root_dir%/../web/receipts_pdf'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
        image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /images
            upload_destination: '%kernel.root_dir%/../web/images'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true

# KnpSnappyBundle
knp_snappy:
    pdf:
        enabled:    true
        binary:     "%wlhtmltopdf_path%"
        options:    []
    image:
        enabled:    true
        binary:     "%wlhtmltoimg_path%"
        options:    []

# JMoseCommandSchedulerBundle
jmose_command_scheduler:
    # Default directory where scheduler will write output files
    #  This default value assume that php bin/console is launched from project's root and that the directory is writable
    # if log_path is set to false, logging to files is disabled at all
    log_path: var/scheduler_logs/
    # This default value disables timeout checking (see monitoring), set to a numeric value (seconds) to enable it
    lock_timeout: false
    # receivers for reporting mails
    monitor_mail: []
    # to send "everything's all right" emails to receivers for reporting mails set this value to "true" (see monitoring)
    send_ok: false

    # Namespaces listed here won't be listed in the list
    excluded_command_namespaces:
        - _global
        - scheduler
        - server
        - container
        - config
        - generate
        - init
        - router

    # Doctrine manager
    doctrine_manager: default

#Twilio
vresh_twilio:
    #(Required) Your Account SID from www.twilio.com/user/account
    sid: 'AC75f34ca68fdf6a4aef16a6ead523152d'
    #(Required) Your Auth Token from www.twilio.com/user/account
    authToken: '8e663558b95c976d258d30b74252a7a5'
    #(Optional, default: '2010-04-01') Twilio API version
    version: '2010-04-01'
    #(Optional, default: 1) Number of times to retry failed requests
    retryAttempts: 3

#EasyAdminBundle
easy_admin:
    site_name: 'Cliniquecoderre.com'
    design:
        menu:
            - { label: 'Dashboard' }
            - { label: 'Accueil', icon: 'desktop', route: 'easyadmin', default: true }
            - { entity: 'Client', icon: 'users', label: 'menu.client' }
            - { entity: 'Employe', icon: 'users', label: 'menu.employe' }
            - label: 'Horaire'
              icon: 'calendar'
              children:
                - { entity: 'Event', icon: 'calendar', label: 'menu.appointment' }
            #- { entity: 'Event', label: 'menu.appointment_new', icon: 'calendar-plus-o', params: { action: 'new' } }
            - { entity: 'Communication', icon: 'envelope', label: 'menu.communication' }
        form_theme:
          - horizontal
          - easy_admin/_form_theme.html.twig
        assets:
            css: ['/plugin/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css', 'https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.2.0/fullcalendar.min.css', '/css/easyadmin/stylesheet.css', 'css/calendar.css']
    list:
        actions:
            - { name: 'edit', icon: 'pencil' }
    entities:
        Client:
            class: AppBundle\Entity\Client
            controller: AppBundle\Controller\EasyAdmin\ClientController
            search:
                sort: ['createdAt', 'DESC']
            list:
                fields:
                    - { property: 'firstname', label: 'client.firstname' }
                    - { property: 'lastname', label: 'client.lastname' }
                    - { property: 'gender', label: 'client.gender' }
                    - { property: 'user', label: 'client.email' }
                    - { property: 'phonecell', label: 'general.info.phoneCell', template: 'easy_admin/field_phone.html.twig' }
                    - { property: 'createdAt', label: 'admin.client.table.createdat' }
            form:
                fields:
                    - { type: 'group', label: 'Information général', css_class: 'col-sm-6' }
                    - { property: 'firstname', label: 'client.firstname' }
                    - { property: 'lastname', label: 'client.lastname' }
                    - { property: 'birthdate', type_options: { widget: 'single_text', format: 'yyyy-MM-dd', attr: {'class': 'birthdate_datepicker '} } }
                    - { property: 'gender', type: 'choice', type_options: { placeholder: false, choices: { Homme:'Homme', Femme:'Femme' } } }
                    - { type: 'section', label: 'Adresse', icon: 'address-card' }
                    - { property: 'coordinates', css_class: 'collection_wrapper', type: collection, type_options: { entry_type: 'AppBundle\Form\CoordinateType', allow_add: false, allow_delete: false, by_reference: false } }
                    - { type: 'group', label: 'Information de contact', css_class: 'col-sm-6' }
                    - { type: 'section', label: 'Usager', icon: 'user' }
                    - { property: 'email', type: 'email', type_options: { required: true, mapped: false } }
                    - { type: 'section', label: 'Contact', icon: 'phone' }
                    - { property: 'contacts', css_class: 'collection_wrapper', type: collection, type_options: { entry_type: 'AppBundle\Form\ContactType', allow_add: false, allow_delete: false, by_reference: false, required: true } }
            edit:
                titles: 'New %%entity.firstname%%'
                fields:
                    - { property: 'email', type: 'text', type_options: { required: true, disabled: true, mapped: true} }
        Employe:
            class: AppBundle\Entity\Employe
            controller: AppBundle\Controller\EasyAdmin\EmployeController
            list:
                fields:
                    - { property: 'firstname', label: 'employe.firstname' }
                    - { property: 'lastname', label: 'employe.lastname' }
                    - { property: 'user', label: 'employe.email' }
                    - { property: 'phonecell', label: 'general.info.phoneCell', template: 'easy_admin/field_phone.html.twig' }
                    - { property: 'createdAt', label: 'admin.employe.table.createdat' }
            form:
                fields:
                    - { type: 'group', label: 'Information général', css_class: 'col-sm-6' }
                    - { property: 'firstname', label: 'employe.firstname' }
                    - { property: 'lastname', label: 'employe.lastname' }
                    - { property: 'birthdate', type_options: { widget: 'single_text', format: 'yyyy-MM-dd', attr: {'class': 'birthdate_datepicker '} } }
                    - { property: 'gender', type: 'choice', type_options: { placeholder: false, choices: { Homme:'Homme', Femme:'Femme' } } }
                    - { type: 'section', label: 'Adresse', icon: 'address-card' }
                    - { property: 'coordinates', css_class: 'collection_wrapper', type: collection, type_options: { entry_type: 'AppBundle\Form\CoordinateType', allow_add: false, allow_delete: false, by_reference: false } }
                    - { type: 'group', label: 'Information de contact', css_class: 'col-sm-6' }
                    - { type: 'section', label: 'Usager', icon: 'user' }
                    - { property: 'email', type: 'text', type_options: { required: true, mapped: false } }
                    - { type: 'section', label: 'Contact', icon: 'phone' }
                    - { property: 'contacts', css_class: 'collection_wrapper', type: collection, type_options: { entry_type: 'AppBundle\Form\ContactType', allow_add: false, allow_delete: false, by_reference: false } }
            edit:
                titles: 'New %%entity.firstname%%'
                fields:
                    - { property: 'email', type: 'text', type_options: { required: true, disabled: true, mapped: true} }
        Event:
            class: AppBundle\Entity\Event
            controller: AppBundle\Controller\EasyAdmin\EventController
            list:
                dql_filter: 'entity.emergency = true'
                fields:
                    - { property: 'client', label: 'general.info.name' }
                    - { property: 'startTime', label: 'admin.event.table.startTime' }
                    - { property: 'emergency', label: 'admin.event.table.emergency', type: 'boolean' }
                    - { property: 'receipts[0]', label: 'admin.event.table.receipt', template: 'easy_admin/Event/show_receipt.html.twig', base_path: 'receipts_pdf' }
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'client' }
                    - { property: 'employe' }
                    - { property: 'startTime', type_options: { widget: 'single_text', format: 'yyyy-MM-dd HH:mm', html5: false, attr: {'class': 'event_datetimepicker '} } }
        Communication:
            class: AppBundle\Entity\Communication
            controller: AppBundle\Controller\EasyAdmin\CommunicationController
            list:
                fields:
                    - title
                    - dateSent
                    - { property: 'clients', type_options: { class: 'AppBundle\Entity\Client', choice_label: 'getFullNameEmailPhoneToString' } }
                actions:
                    - -edit
                    - -delete
            form:
                title: 'admin.communication.title'
                fields:
                    - { property: 'title' }
                    - { property: 'content' }
                    - { property: 'clients', type_options: { class: 'AppBundle\Entity\Client', choice_label: 'getFullNameEmailPhoneToString', expanded: true, multiple: true, attr: {'class': 'event_datetimepicker '} } }
                    - property: 'type'
                      type: 'choice'
                      type_options: {
                          choices: [ {email: 'email', sms: 'sms'} ],
                          multiple: true,
                          expanded: true }
