app:
    resource: "@AppBundle/Controller/"
    type:     annotation

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /admin/dashboard/

easy_admin_bundle:
    resource: "@AppBundle/Controller/EasyAdmin/AdminController.php"
    type:     annotation
    prefix:   /easyadmin

craue_config_settings:
  resource: "@CraueConfigBundle/Resources/config/routing/settings.xml"
  prefix: /settings

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"