# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.calendar_listener:
        class: AppBundle\EventListener\CalendarEventListener
        arguments: ['@doctrine.orm.entity_manager', '@libphonenumber.phone_number_util']
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }

    app.communication_mailer:
        class: AppBundle\Service\CommunicationMailerService
        arguments: ['@mailer']

    app.appointment_subscriber:
        class: AppBundle\Subscriber\AppointmentSubscriber
        arguments: ['@app.appointment_manager']
        tags:
            - { name: kernel.event_subscriber }
    app.appointment_manager:
        class: AppBundle\Manager\AppointmentManager
        arguments: ['@doctrine.orm.entity_manager', '@templating', '@session', '@app.communication_mailer', '@libphonenumber.phone_number_util']

    app.schedule_manager:
        class: AppBundle\Manager\ScheduleManager
        arguments: ['@doctrine.orm.entity_manager']