# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.calendar_listener:
        class: AppBundle\EventListener\CalendarEventListener
        arguments: ['@doctrine.orm.entity_manager', '@libphonenumber.phone_number_util', '@translator']
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }

    app.communication_mailer:
        class: AppBundle\Service\CommunicationMailerService
        arguments: ['@service_container', '@mailer', '@twilio.api', '@libphonenumber.phone_number_util']

    app.appointment_subscriber:
        class: AppBundle\Subscriber\AppointmentSubscriber
        arguments: ['@app.appointment_manager']
        tags:
            - { name: kernel.event_subscriber }
    app.appointment_manager:
        class: AppBundle\Manager\AppointmentManager
        arguments: ['@doctrine.orm.entity_manager', '@templating', '@session', '@app.communication_mailer', '@libphonenumber.phone_number_util','@translator']

    app.schedule_manager:
        class: AppBundle\Manager\ScheduleManager
        arguments: ['@doctrine.orm.entity_manager']

    app.client_subscriber:
        class: AppBundle\Subscriber\ClientSubscriber
        arguments: ['@app.client_manager']
        tags:
            - { name: kernel.event_subscriber }

    app.easy_admin_subscriber:
        class: AppBundle\Subscriber\EasyAdminSubscriber
        arguments: ['@security.token_storage']
        tags:
            - { name: kernel.event_subscriber }

    app.client_manager:
            class: AppBundle\Manager\ClientManager
            arguments: ['@doctrine.orm.entity_manager', '@templating', '@session', '@app.communication_mailer', '@libphonenumber.phone_number_util', '@router','@translator']

    app.communication_manager:
                class: AppBundle\Manager\CommunicationManager
                arguments: ['@doctrine.orm.entity_manager', '@app.communication_mailer']


    app.communication_subscriber:
        class: AppBundle\Subscriber\CommunicationSubscriber
        arguments: ['@app.communication_manager']
        tags:
            - { name: kernel.event_subscriber }